name: MineverseChat
version: 1.5.1
main: mineverse.Aust1n46.chat.MineverseChat
depend: [Vault]
softdepend: [Jobs, Towny, Factions]
Author: Aust1n46
description: Chat with channels with many features!
commands:
    mute:
        usage: /mute [playername] [channel]
        aliases: [mp]
        description: Mutes player in a channel so they cannot talk.
        permission-message: You don't have <permission>
    unmute:
        usage: /unmute [playername] [channel]
        aliases: [ump]
        description: Unmutes player in a channel so they can talk again.
        permission-message: You don't have <permission>
    tell:
        usage: /tell [playername] [msg]
        aliases: []
        description: Send a message to a player
        permission-message: You don't have <permission>
    ignore:
        usage: /ignore [playername] or /ignore ? for more information
        aliases: []
        description: This allows you to prevent a player from sending you a tell /ignore list to see who you have ignored
        permission-message: You don't have <permission>
    whisper:
        usage: /whisper [playername] [msg]
        aliases: [w]
        description: Send a message to a player
        permission-message: You don't have <permission>
    channel:
        usage: /channel [channelname]
        aliases: [ch]
        description: Allows players to add the ability to listen to the channel
        permission-message: You don't have <permission>
    leave:
        usage: /leave [channelname]
        aliases: [lev]
        description: Allows players to leave listening to a channel
        permission-message: You don't have <permission>
    join:
        usage: /join [channelname]
        description: Allows players to join a channel
        permission-message: You don't have <permission>
    chlist:
        usage: /chlist
        aliases: [chl]
        description: Allows players to see a listing of available channels
        permission-message: You don't have <permission>
    chwho:
        usage: /chwho [channelname]
        aliases: [chw]
        description: Allows players to see a listing of who is listening on a channel
        permission-message: You don't have <permission>
    setchannel:
        usage: /setchannel [playername] [channel]
        aliases: [sc]
        description: Sets a players channel
        permission-message: You don't have <permission>
    kickchannel:
        usage: /kickchannel [playername] [channel]
        aliases: [kc]
        description: Kicks a player out of a channel
        permission-message: You don't have <permission>
    message:
        usage: /message [playername] [msg]
        aliases: [msg,pm]
        description: Send a message to a player
    muteall:
        usage: /muteall [playername]
        aliases: [mpa]
        description: Mute a player in all channels
        permission-message: You don't have <permission>
    unmuteall:
        usage: /unmuteall [playername]
        aliases: [umpa]
        description: Unmute a player in all channels
        permission-message: You don't have <permission>
    kickchannelall:
        usage: /kickchannelall [playername]
        aliases: [kca]
        description: Kick a player from all channels
        permission-message: You don't have <permission>
    setchannelall:
        usage: /setchannelall [playername]
        aliases: [sca]
        description: Set a player into all channels
        permission-message: You don't have <permission>
    force:
        usage: /force [playername] [message]
        aliases: [for]
        description: Force a player to chat or execute a command
        permission-message: You don't have <permission>
    forceall:
        usage: /forceall [message]
        aliases: [fora]
        description: Force all players to chat or execute a command
        permission-message: You don't have <permission>
    listen:
        usage: /listen [channel]
        aliases: [lis]
        description: Listen to a channel without setting it as the one your chatting in
        permission-message: You don't have <permission>
    chatreload:
        usage: /chatreload
        aliases: [cr]
        description: Reload the config file
        permission-message: You don't have <permission>
    afk:
        usage: /afk
        aliases: []
        description: Set yourself as afk
        permission-message: You don't have <permission>
    reply:
        usage: /reply [msg]
        aliases: [r]
        description: Reply to a message
        permission-message: You don't have <permission>
    spy:
        usage: /spy
        aliases: []
        description: Spy on tells
        permission-message: You don't have <permission>
    commandspy:
        usage: /commandspy
        aliases: [comspy]
        description: Spy on commands
        permission-message: You don't have <permission>
    chatinfo:
        usage: /chatinfo
        aliases: [ci]
        description: Check a players chat info
        permission-message: You don't have <permission>
    channelinfo:
        usage: /channelinfo
        aliases: [chi]
        description: Check a channels info
        permission-message: You don't have <permission>
    mineversechat:
        usage: /mineversechat
        aliases: [mc]
        description: Check plugin information
        permission-message: You don't have <permission>
    me:
        usage: /me
        aliases: []
        description: Send an emote
        permission-message: You don't have <permission>
    filter:
        usage: /filter
        aliases: [fil]
        description: Toggle filter on and off
        permission-message: You don't have <permission>
    broadcast:
        usage: /broadcast [msg]
        aliases: [bc]
        description: Broadcast a message
        permission-message: You don't have <permission>
    commandblock:
        usage: /commandblock [player] [command]
        aliases: [cb]
        description: Toggle a player blocked from entering a command
        permission-message: You don't have <permission>
    party:
        usage: /party help
        aliases: [p,chatparty,cp]
        description: Party commands
        permission-message: You don't have <permission>
    edit:
        usage: /edit help
        aliases: []
        description: Edit commands
        permission-message: You don't have <permission>
